version: '2.1'

orbs:
  browser-tools: circleci/browser-tools@1.4.3

executors:
  my-custom-executor:
    docker:
      - image: python:3.9
        auth:
          # Ensure you have first added these secrets
          # Visit app.circleci.com/settings/project/github/gabriel-nds/WebScrapingGloboEsporte/environment-variables
          username: $globoesporte  
          password: $globoesportekey

jobs:
  ge-flamengo-spider:
    executor: my-custom-executor
    steps:
      - checkout

      # Move the pip install command to before the "Run Spider" step to avoid reinstalling on every run
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      # Add the following steps to install Chrome browser and ChromeDriver
      - browser-tools/install-chrome
      - run:
          name: Install ChromeDriver
          command: |
            CHROME_DRIVER_PATH="/usr/local/bin"  # Set the installation path for ChromeDriver
            export CHROME_DRIVER_PATH
            browser-tools/install-chromedriver

      - run:
          name: Run Spider
          command: scrapy crawl globoesporte

workflows:
  my-custom-workflow:
    jobs:
      - ge-flamengo-spider
