version: '2.1'

orbs:
  browser-tools: circleci/browser-tools@1.4.3

executors:
  my-custom-executor:
    docker:
      - image: python:3.9
        auth:
          username: $globoesporte  
          password: $globoesportekey

jobs:
  ge-flamengo-spider:
    executor: my-custom-executor
    steps:
      - checkout
          
      # Move the pip install command to before the "Run Spider" step to avoid reinstalling on every run
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      
      # Add the following steps to install Chrome browser
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver

            
      - run:
          name: Run Spider
          # command: scrapy crawl globoesporte
          command: scrapy crawl globoesporte > chrome_output.txt 2>&1

workflows:
  my-custom-workflow:
    jobs:
      - ge-flamengo-spider
