version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: python:3.9
        auth:
          # Ensure you have first added these secrets
          # Visit app.circleci.com/settings/project/github/gabriel-nds/WebScrapingGloboEsporte/environment-variables
          username: $GE_SPIDER_VAR
          password: $ge-value-usd\\$

jobs:
  ge-flamengo-spider:
    executor: my-custom-executor
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt

      - run:
          name: Install Chrome and Chrome WebDriver
          command: |
            apt-get update
            apt-get install -y wget
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
            apt-get update
            apt-get install -y google-chrome-stable
            LATEST_CHROMEDRIVER_VERSION=$(curl -sS https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
            wget -q -N https://chromedriver.storage.googleapis.com/$LATEST_CHROMEDRIVER_VERSION/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip -d /usr/local/bin
            chmod +x /usr/local/bin/chromedriver

      - run:
          name: Run Spider
          command: scrapy crawl globoesporte

workflows:
  my-custom-workflow:
    jobs:
      - ge-flamengo-spider
