version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: python:3.9
        auth:
          # Ensure you have first added these secrets
          # Visit app.circleci.com/settings/project/github/gabriel-nds/WebScrapingGloboEsporte/environment-variables
          username: $globoesporte  
          password: $globoesportekey

jobs:
  ge-flamengo-spider:
    executor: my-custom-executor
    steps:
      - checkout

      # Add the following steps to install Chrome browser
      - run:
          name: Install Chrome
          command: |
            sudo apt-get update
            sudo apt-get install -y wget gnupg2
            wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
            echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google.list
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable

      # Move the pip install command to before the "Run Spider" step to avoid reinstalling on every run
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      
      - run:
          name: Run Spider
          command: scrapy crawl globoesporte

workflows:
  my-custom-workflow:
    jobs:
      - ge-flamengo-spider