version: '2.1'

orbs:
  browser-tools: circleci/browser-tools@1.4.3

executors:
  my-custom-executor:
    docker:
      - image: circleci/python:3.9
    working_directory: ~/repo
  my-custom-executor-with-chrome:
    docker:
      - image: circleci/python:3.9
      - image: circleci/chrome:115.0.5790.114-20230201

jobs:
  ge-flamengo-spider:
    executor: my-custom-executor-with-chrome
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run Spider
          command: scrapy crawl globoesporte

workflows:
  my-custom-workflow:
    jobs:
      - ge-flamengo-spider
