version: '2.1'

orbs:
  browser-tools: circleci/browser-tools@1.4.3

executors:
  my-custom-executor:
    docker:
      - image: python:3.9
      
      # Add the custom Chrome version to the executor
      - image: circleci/chrome:115.0.5790.114-20230201
      
    auth:
      # Ensure you have first added these secrets
      # Visit app.circleci.com/settings/project/github/gabriel-nds/WebScrapingGloboEsporte/environment-variables
      username: $globoesporte  
      password: $globoesportekey

jobs:
  ge-flamengo-spider:
    executor: my-custom-executor
    steps:
      - checkout
      
      # Move the pip install command to before the "Run Spider" step to avoid reinstalling on every run
      - run:
          name: Install Dependencies
          command: |
            pip install -r requirements.txt
      
      - run:
          name: Run Spider
          command: scrapy crawl globoesporte

workflows:
  my-custom-workflow:
    jobs:
      - ge-flamengo-spider
